version: '3.9'

# Below I define the two services I need for my app:
# - a postgres (database) service to store data into
# - a jupyterlab service: un work environment where I'll be using python and 
# - SQL to Build ETL pipeline and interact with postgres
services:
  pgdb: # this is the name of postgres service
    image: postgres
    container_name: postgres_container
    env_file: 
      # this file contain the secret credentials to connect to the database
      - database.env
    ports:
      # binding the port 5432 in the container (right) with the same port in the
      # the host machine
      - '5432:5432'
    restart: always # making sure that postgres will always run
  jlab: # this is the name of jupyter lab service
    # this container will be built based on the dockerfile
    # in the current directory '.'
    build: .
    container_name: jupyter_container
    # when this container is running the command below will be executed
    # --no-browser: don't try to open the browser automatically
    # --ip=0.0.0.0: accept request from any ip
    # --allow-root: allow root user (the default user in the container) 
    # to launch jupyterlab
    command: jupyter lab --no-browser --ip=0.0.0.0 --allow-root
    ports:
      - '8888:8888'
    volumes:
      - ./notebook:/notebook
    depends_on:
      # this will handle the communication between the two services. Therefore
      # pgdb will always first run before jlab and we can connect to postgres 
      # using the hostname 'pgdb' instead of 'localhost' or '127.0.0.0'.
      - pgdb